FROM ubuntu:18.04

ARG NB_USER="spinnaker"
ARG NB_UID="1000"
ARG NB_GID="100"

USER root

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ENV DEBIAN_FRONTEND noninteractive

# Add some repositories
RUN apt-get update && apt-get install -y software-properties-common wget sudo
RUN wget -O - https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add - \
    && apt-add-repository "deb http://packages.ros.org/ros/ubuntu bionic main" \
    && wget -O - http://packages.osrfoundation.org/gazebo.key | sudo apt-key add - \
    && sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list' \
    && add-apt-repository ppa:openjdk-r/ppa 

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    curl git python python-dev python3.6 python3.6-dev python3.6-tk python3.6-distutils build-essential unzip libxext-dev libsm6 libxrender1 \
    gcc-arm-none-eabi libnewlib-arm-none-eabi \
    bzip2 ca-certificates locales fonts-liberation run-one nano less iputils-ping \
    openjdk-11-jdk maven \
    && apt-get -y autoremove \
    && apt-get -y clean  \
    && rm -rf /var/lib/apt/lists/*

# Override older python version with 3.6
RUN rm /usr/bin/python3 \
    && ln -s /usr/bin/python3.6 /usr/bin/python3 \
    && ln -s /usr/bin/pip3.6 /usr/bin/pip3

# Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && apt-get update && apt-get install -y nodejs

# Update the Locale
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
    
# Add a script that we will use to correct permissions after running certain commands
ADD fix-permissions /usr/local/bin/fix-permissions
    
# Configure environment
ENV SHELL=/bin/bash \
    NB_USER=$NB_USER \
    NB_UID=$NB_UID \
    NB_GID=$NB_GID \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8
ENV HOME=/home/$NB_USER

# Create NB_USER with UID=1000 and in the 'users' group
# and make sure these dirs are writable by the `users` group.
RUN echo "auth requisite pam_deny.so" >> /etc/pam.d/su && \
    sed -i.bak -e 's/^%admin/#%admin/' /etc/sudoers && \
    sed -i.bak -e 's/^%sudo/#%sudo/' /etc/sudoers && \
    useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
    chmod g+w /etc/passwd && \
    fix-permissions $HOME

# Install Pip in Python 2 and 3
RUN curl -O https://bootstrap.pypa.io/get-pip.py \
    && python2 get-pip.py \
    && python3 get-pip.py \ 
    && rm get-pip.py \
    && pip2 --no-cache-dir install requests[security]
    
# Install Tini
ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /bin/tini
RUN chmod ugo+x /bin/tini

# Install Jupyter Notebook, Lab, and Hub
# Generate a notebook server config
# Cleanup temporary files
# Correct permissions
# Do all this in a single RUN command to avoid duplicating all of the
# files across image layers when the permissions change
RUN pip3 --no-cache-dir install --pre \
    'notebook==6.0.3' \
    'jupyterhub==1.0.0' \
    'jupyterlab==2.1.1' \
    'jupyterlab-git==0.20.0rc0' \
    ipympl jupyter-server-proxy \
    && jupyter notebook --generate-config \
    && rm -rf $HOME/.cache/yarn \
    && fix-permissions $HOME \
    && jupyter serverextension enable --py jupyterlab_git \
    && jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib \
    && jupyter nbextension enable --py widgetsnbextension \
    && jupyter lab build

EXPOSE 8888

# Configure container startup
ENTRYPOINT ["tini", "-g", "--"]
CMD ["start-notebook.sh"]

COPY jupyter_notebook_config.py /etc/jupyter/

RUN pip3 --no-cache-dir install --upgrade ipykernel \
    && pip3 --no-cache-dir install virtualenv \
    && pip2 --no-cache-dir install --upgrade ipykernel ipympl \
    && pip2 --no-cache-dir install 'virtualenv<20.0.0'

RUN rm -rf $HOME/.cache $HOME/.config

# Switch back to user to avoid accidental container runs as root
USER $NB_USER
WORKDIR $HOME

RUN ipython profile create spynnaker
RUN echo "c.InteractiveShellApp.matplotlib = 'ipympl'" >> .ipython/profile_spynnaker/ipython_kernel_config.py

RUN python3 -m virtualenv sPyNNaker
ADD --chown=1000:users activate $HOME/sPyNNaker/bin/
RUN /bin/bash -c "source sPyNNaker/bin/activate \
                  && pip install numpy scipy matplotlib ipympl pyNN==0.9.4 \
                  && pip install ipykernel spynnaker8 \
                  && python -m spynnaker8.setup_pynn \
                  && python -m ipykernel install --user --name sPyNNaker --profile spynnaker"

RUN python3 -m virtualenv sPyNNakerGit
ADD --chown=1000:users activate $HOME/sPyNNakerGit/bin/
WORKDIR $HOME/sPyNNakerGit
RUN git clone https://github.com/SpiNNakerManchester/SupportScripts.git support \
    && support/install.sh 8 -y \
    && /bin/bash -c "source bin/activate && cd SpiNNUtils && python setup.py develop"
RUN /bin/bash -c "source bin/activate \
                  && pip install ipykernel matplotlib ipympl pyNN \
                  && support/automatic_make.sh \
                  && support/setup.sh \
                  && python -m spynnaker8.setup_pynn \
                  && python -m ipykernel install --user --name sPyNNakerGit --profile spynnaker"
WORKDIR $HOME

# Install the HBP NRP
USER root
RUN apt-get update && apt-get install -y cmake g++ gcc make curl libz-dev xvfb python-opengl libgl1-mesa-dev libharfbuzz-dev \
    && apt-get install -y cmake python-h5py python-lxml build-essential doxygen autogen automake libtool autoconf libltdl7-dev libtinyxml-dev libreadline6-dev libncurses5-dev libgsl0-dev python-all-dev python-docopt libxslt1-dev zlib1g-dev libfreetype6-dev python-opencv ruby libtar-dev libprotoc-dev protobuf-compiler imagemagick libtinyxml2-dev libffi-dev uwsgi-plugin-python cimg-dev libgnuplot-iostream-dev openssh-client
USER $NB_USER
ENV HBP=$HOME/Documents/NRP
ENV NRP_INSTALL_MODE=user
RUN mkdir -p $HBP
WORKDIR $HBP
RUN git clone https://bitbucket.org/hbpneurorobotics/user-scripts.git --branch=master18
WORKDIR $HBP/user-scripts
RUN ./clone-all-repos
RUN echo "export PYTHONPATH=" >> $HOME/.bashrc \
    && echo ". $HBP/user-scripts/nrp_variables" >> $HOME/.bashrc \
    && echo ". $HBP/user-scripts/nrp_aliases" >> $HOME/.bashrc
USER root
RUN apt-get update && apt-get install --allow-unauthenticated -y ros-melodic-desktop-full ros-melodic-web-video-server ros-melodic-control-toolbox ros-melodic-controller-manager ros-melodic-transmission-interface ros-melodic-joint-limits-interface ros-melodic-rosauth ros-melodic-smach-ros python-rospkg python-rosdep \
    && apt-get remove -y --purge gazebo9* libgazebo9* ros-melodic-gazebo*
RUN rosdep init
RUN apt-get update && apt-get install -y libignition-math6-dev libignition-transport-dev libignition-transport4-dev \
    libsimbody-dev libgts-dev libgdal-dev ruby-ronn xsltproc graphviz-dev \
    libgsl0-dev bison byacc \
    libgts-dev libjansson-dev \
    libblas-dev liblapack-dev libhdf5-dev gfortran \
    nginx-extras lua-cjson \
    ruby-compass
WORKDIR $HBP/ExDFrontend
RUN gem install compass
USER $NB_USER
RUN rosdep update
ENV USER=$NB_USER
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | /bin/bash
ENV NVM_DIR=$HOME/.nvm
RUN /bin/bash -i -c "nvm install 8 && nvm alias default 8 && npm install -g bower"
WORKDIR $HBP/user-scripts
RUN /bin/bash -i -c "./configure_nrp 2>/dev/null"
WORKDIR $HBP/ExDFrontend
RUN /bin/bash -i -c "npm install -g grunt-cli && npm install -g grunt"
WORKDIR $HBP/user-scripts
RUN /bin/bash -i -c "./configure_nrp"

# Magic to make the camera work in Xvfb
ENV DISPLAY=:0
RUN sed -Ez 's|(\s*)(#if OGRE_VERSION_MAJOR == 1 && OGRE_VERSION_MINOR < 8\n)(\s*fsaa = 0;\n\s*)(#endif)|\1//\2\3//\4|' -i $HBP/gazebo/gazebo/rendering/Camera.cc
RUN /bin/bash -i -c "./update_nrp build all && ./rendering_mode cpu"

# Here be magic to fix for JupyterHub
ADD --chown=1000:users nginx.conf $HBP/user-scripts/config_files/nginx/nginx.conf
RUN sed -e 's\http://localhost:9000/proxy\../9000/proxy\' -i $HBP/user-scripts/config_files/ExDFrontend/config.json.local
RUN /bin/bash -i -c "./configure_nrp \
                     && cd $HBP/ExDFrontend \
                     && npm install --no-save && grunt build"
RUN /bin/bash -i -c "source $HOME/.opt/platform_venv/bin/activate \
                     && pyxbgen -u $HBP/user-scripts/migrate_xmltf/xsd/xml-tf-bibi.xsd -m $HBP/user-scripts/migrate_xmltf/lib/bibi_api_gen \
                     && deactivate"

# Add SpiNNaker to NRP
WORKDIR $HOME/.opt/platform_venv
ADD --chown=1000:users activate $HOME/.opt/platform_venv/bin/
RUN git clone https://github.com/SpiNNakerManchester/SupportScripts.git support \
    && support/install.sh 8 -y
RUN /bin/bash -c "source bin/activate \ 
                  && cd SpiNNUtils \
                  && python setup.py develop"
RUN /bin/bash -c "source bin/activate \
                  && pip install --upgrade pip \
                  && pip install ipykernel matplotlib pyNN \
                  && pip uninstall -y lazyarray \
                  && support/automatic_make.sh \
                  && support/setup.sh \
                  && python -m spynnaker8.setup_pynn \
                  && pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade numpy"

# Change to working version of NRP
WORKDIR $HBP
RUN cd ExDBackend && git remote add agdr https://bitbucket.org/agdr/exdbackend.git && git fetch agdr spinnaker_master18 && git checkout spinnaker_master18

USER root
RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \
       --recv-keys 8756C4F765C9AC3CB6B85D62379CE192D401AB61 \
    && echo deb http://deb.seadrive.org bionic main | \
       sudo tee /etc/apt/sources.list.d/seafile.list \
    && apt-get update \
    && apt-get install -y seadrive-daemon strace

COPY start.sh /usr/local/bin/
COPY start-notebook.sh /usr/local/bin/
COPY start-singleuser.sh /usr/local/bin/

USER $NB_UID
WORKDIR $HOME

# Make NRP storage visible from within Jupyter
RUN ln -s $HOME/.opt/nrpStorage nrpStorage

RUN echo ". $HOME/.updateuser.sh" >> $HOME/.bashrc
RUN echo ". $HBP/user-scripts/fix_nrp.sh " >> $HOME/.bashrc

# Add local files as late as possible to avoid cache busting
ADD --chown=1000:users fix_nrp.sh $HBP/user-scripts/fix_nrp.sh
ADD --chown=1000:users run_xvfb.sh $HBP/user-scripts/run_xvfb.sh
ADD --chown=1000:users updateuser.sh $HOME/.updateuser.sh
ADD --chown=1000:users .spynnaker.cfg $HOME
ADD --chown=1000:users SpaceInvaders.ipynb $HOME
ADD --chown=1000:users SynfireExample.ipynb $HOME
ADD --chown=1000:users 01.RunningPyNNSimulations $HOME/01.RunningPyNNSimulations
ADD --chown=1000:users 02.LiveInputAndOutput $HOME/02.LiveInputAndOutput
ADD --chown=1000:users 03.NeuroroboticsPlatform $HOME/03.NeuroroboticsPlatform
